"""add ripple_resources and ripple_moderations tables

Revision ID: 4afa621d6930
Revises: d073b3a4733a
Create Date: 2026-03-04 13:09:48.402211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4afa621d6930'
down_revision: Union[str, None] = 'd073b3a4733a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
