"""add additional_notes to assignments

Revision ID: d073b3a4733a
Revises: 09075fc40212
Create Date: 2026-03-04 12:22:07.219196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd073b3a4733a'
down_revision: Union[str, None] = '09075fc40212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('additional_notes', sa.Text(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'additional_notes')
    # ### end Alembic commands ###
