"""add marking_mode to assignments

Revision ID: e252b2ac2e77
Revises: 1511221c16df
Create Date: 2026-03-13 09:46:50.016569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e252b2ac2e77'
down_revision: Union[str, None] = '1511221c16df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('marking_mode', sa.String(length=32), nullable=False, server_default='teacher_supervised_ai'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'marking_mode')
    # ### end Alembic commands ###
